### ISSUE TITLE
Return Vimeo URL after uploading file from front end.

### ISSUE THREAD

**Issue by blackb2b** [gdarko/wp-vimeo-videos#6] opened 2020-09-24 01:38 UTC
I just purchased your plugin. I am trying to configure so make it works compatible with our theme. I have two issues with Uploading Video from front end.

1. Currently, when I set Admin Field in Gravity Form setting as our custom field, it return the video file path instead of Vimeo URL. Can I get Vimeo URL?

2. Progress bar which is working on default File upload is not supported for Vimeo Upload. I am unhappy with this. Is there any a workaround for it?

Best regards,

**Comment by gdarko** [comment] 2020-09-24 05:40
Hello,

1.) Can you send us a screenshot of the issue on email info@codeverve.com ?
2.) Progress bar is not available for the front-end uploads for security reasons. Unfortunately in order to have a progress bar we need to expose the access token in the front-end in order to be able to use the Viemo Javascript libraries to make it nice. However this is huge concern and if someone steal your access token they can delete, upload or do whatever they want with your account.

Thanks

**Comment by blackb2b** [comment] 2020-09-24 05:50
Hi,

1. You can check the image here. As you can see, I need the Vimeo URL is filled up at Video URL instead of file path at Video File.

https://imgur.com/a/w59HhuP

2. Yes, I noticed that your plugin does not support progress bar for front end upload. But the plugin will upload video to server first, right? So can we just show the progress bar of uploading file to server step only (supported by default Gravity)?

Best regards,

**Comment by gdarko** [comment] 2020-09-24 05:57
Thanks,

1.) Please send us a login info at info@codeverve.com and we will check. Do you use a plugin to populate the metadata?
2.) We already working on different GravityForms field that will support this, however there is no significant progress at this time. This is planned as separate field and will be released on further major versions once we complete it.

**Comment by blackb2b** [comment] 2020-09-24 07:44
Hi,

1. Ok, I will send you the login information shortly.

2. I can configure to get progress bar on default Gravityform field. Just allow mutiple files upload. I will show you the demo via the site that I am going to send to you.

Best regards,

**Comment by gdarko** [comment] 2020-09-24 09:32
Hi,

Thanks. Yes, the plan is to have similar implementation like the original multi-file progress bar just initially with only one file per field.

Best,
Darko

**Comment by blackb2b** [comment] 2020-09-24 10:02
Yes, do you have ETA for that? 

Also, I just sent you the information for point 1. Can you check it soon?

Thanks in advance!

Best regards,

**Comment by gdarko** [comment] 2020-09-24 17:51
Hi @blackb2b ,

I don't see anything in the email. Did you send it?

We scheduled it for version 1.5. Hopefully in a 1-2 months. I will keep you posted. 

Thanks.

**Comment by blackb2b** [comment] 2020-09-25 08:07
Thanks, I already sent you. My email is g*****.hhtv@gmail.com

Please check.

Best regards,

**Comment by blackb2b** [comment] 2020-09-28 05:04
Hi,

Sorry, can you guys help me on this? I am still waiting for you reply.

Best regards,

**Comment by gdarko** [comment] 2020-09-28 06:00
Hello,

I am not receiving your emails. Can you try to email me at dg@darkog.com

Thanks

**Comment by blackb2b** [comment] 2020-09-28 15:22
Sent!

Please give me a higher priority. I am in a hurry. Thanks!

Best regards,

**Comment by gdarko** [comment] 2020-09-28 16:04
How to reproduce the problem 1?

Thanks.

**Comment by blackb2b** [comment] 2020-09-28 18:03
Hi,

I sent the detailed in both your emails. Can you check and reply me via email system?

Best regards,

**Comment by blackb2b** [comment] 2020-09-29 17:35
You provided the bad support. Can I get a refund?

**Comment by gdarko** [comment] 2020-09-29 17:43
Hi @blackb2b ,

Based on the [terms & conditions](https://codeverve.com/terms-and-conditions/) and due to the nature of the product we do not process refunds.

Also, it's important to read our [support policy](https://codeverve.com/support-policy/) before because your requests doesn't seem to be eligible for support. But we agreed that we will look into what you are asking and we do not guarantee that we will be able to do the integrations you are looking for.

Please note that we don't discuss non-technical topics on this issue tracker. If you want more info send us email.

Thanks.

**Comment by blackb2b** [comment] 2020-09-30 07:11
Thanks.

I got it.

Best regards,

**Closed as completed** 2020-10-20 12:43 UTC
